// authentication reducer
export const SET_AUTH = 'SET_AUTH';
export const UNSET_AUTH = 'UNSET_AUTH';

// authForm reducer
export const SET_FIRSTNAME_FIELD = 'SET_FIRSTNAME_FIELD'; // set value
export const SET_SURNAME_FIELD = 'SET_SURNAME_FIELD'; // set value
export const SET_USERNAME_FIELD = 'SET_USERNAME_FIELD'; // set value
export const SET_PASSWORD_FIELD = 'SET_PASSWORD_FIELD'; // set value
export const SET_FIRSTNAME_VISITED = 'SET_FIRSTNAME_VISITED';
export const SET_SURNAME_VISITED = 'SET_SURNAME_VISITED';
export const SET_USERNAME_VISITED = 'SET_USERNAME_VISITED';
export const SET_PASSWORD_VISITED = 'SET_PASSWORD_VISITED';
export const SET_FIRSTNAME_HTTP_ERROR = 'SET_FIRSTNAME_HTTP_ERROR';
export const SET_SURNAME_HTTP_ERROR = 'SET_SURNAME_HTTP_ERROR';
export const SET_USERNAME_HTTP_ERROR = 'SET_USERNAME_HTTP_ERROR';
export const SET_PASSWORD_HTTP_ERROR = 'SET_PASSWORD_HTTP_ERROR';
export const SET_AUTH_ACTIVE_ACTION = 'SET_AUTH_ACTIVE_ACTION';
export const SET_VISIBLE_REGISTER_FIELDS = 'SET_VISIBLE_REGISTER_FIELDS';
export const UNSET_VISIBLE_REGISTER_FIELDS = 'UNSET_VISIBLE_REGISTER_FIELDS';

// app reducer
export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';
export const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR';
export const UNSET_NETWORK_ERROR = 'UNSET_NETWORK_ERROR';
export const SET_SERVER_ERROR = 'SET_SERVER_ERROR';
export const UNSET_SERVER_ERROR = 'UNSET_SERVER_ERROR';

// main-menu reducer
export const SET_ACTIVE_DROPDOWN = 'SET_ACTIVE_DROPDOWN';
export const UNSET_ACTIVE_DROPDOWN = 'UNSET_ACTIVE_DROPDOWN';
export const SET_HIDDING_DROPDOWN = 'SET_HIDDING_DROPDOWN';
export const UNSET_HIDDING_DROPDOWN = 'UNSET_HIDDING_DROPDOWN';

// user-reducer
export const SET_USER_INFO = 'SET_USER_INFO';

// tasks-reducer
export const SET_TASKS = 'SET_TASKS';
export const SET_ONE_TASK = 'SET_ONE_TASK';
export const DELETE_ONE_TASK = 'DELETE_ONE_TASK';
export const REPLACE_ONE_TASK = 'REPLACE_ONE_TASK';
export const SET_CREATING_TASK = 'SET_CREATING_TASK';
export const UNSET_CREATING_TASK = 'UNSET_CREATING_TASK';
export const SET_NEW_TASK_VALUE = 'SET_NEW_TASK_VALUE';
export const SET_VISIBLE_TASK_DETAILS = 'SET_VISIBLE_TASK_DETAILS';
export const UNSET_VISIBLE_TASK_DETAILS = 'UNSET_VISIBLE_TASK_DETAILS';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';
export const UNSET_ACTIVE_TASK = 'UNSET_ACTIVE_TASK';

// lists-reducer
export const SET_LISTS = 'SET_LISTS';
export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
